// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPZ2m9BZkAuvAacesa5CYlNbRaP0tqU88',
    appId: '1:983519479575:web:21736121519d0f0c2ad952',
    messagingSenderId: '983519479575',
    projectId: 'disasterquickresponseapp',
    authDomain: 'disasterquickresponseapp.firebaseapp.com',
    storageBucket: 'disasterquickresponseapp.firebasestorage.app',
    measurementId: 'G-XZD80Z7GBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYUILRlZ-tgNK1ScmTEBkUkPo4OfBZCVw',
    appId: '1:983519479575:android:1d103159a55193b22ad952',
    messagingSenderId: '983519479575',
    projectId: 'disasterquickresponseapp',
    storageBucket: 'disasterquickresponseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-E2lM6k7fsLO_xDEdtk53zyCMIYJUK0',
    appId: '1:983519479575:ios:438a72c7a78836112ad952',
    messagingSenderId: '983519479575',
    projectId: 'disasterquickresponseapp',
    storageBucket: 'disasterquickresponseapp.firebasestorage.app',
    iosBundleId: 'com.dqra.rescuer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-E2lM6k7fsLO_xDEdtk53zyCMIYJUK0',
    appId: '1:983519479575:ios:438a72c7a78836112ad952',
    messagingSenderId: '983519479575',
    projectId: 'disasterquickresponseapp',
    storageBucket: 'disasterquickresponseapp.firebasestorage.app',
    iosBundleId: 'com.dqra.rescuer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPZ2m9BZkAuvAacesa5CYlNbRaP0tqU88',
    appId: '1:983519479575:web:21736121519d0f0c2ad952',
    messagingSenderId: '983519479575',
    projectId: 'disasterquickresponseapp',
    authDomain: 'disasterquickresponseapp.firebaseapp.com',
    storageBucket: 'disasterquickresponseapp.firebasestorage.app',
    measurementId: 'G-XZD80Z7GBM',
  );

}